"""empty message

Revision ID: 963219d45bcd
Revises: 27d8c0261ee2
Create Date: 2020-12-16 00:48:39.134242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '963219d45bcd'
down_revision = '27d8c0261ee2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show_info',
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('start_time')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('show_info')
    # ### end Alembic commands ###
